#!/usr/bin/env bash

#set -o xtrace -o errexit
set -o errexit

# don't cd before the line below
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

ZSH_PLUGINS_PATH="${HOME}/.zsh_plugins"
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
if [[ "${OS}" == "linux" ]]; then
    OS=$(uname -n | tr '[:upper:]' '[:lower:]')
fi

_draw_spacer() { echo "+++++++++ +++++++++ +++++++++ +++++++++"; echo; echo; }
_draw_title() { echo "+++++++++ ${1} +++++++++"; echo; echo; }
_show_message_mise() {
    cat <<"EOF"
    command -v mise &>/dev/null && {
        # keep this activation order
        eval "$(mise activate zsh --shims)"
        eval "$(mise activate zsh)"

        eval "$(mise hook-env -s zsh)"
        rehash
        LOADED+=("mise")
    }
EOF
}
_install_zsh_plugins() {
    _draw_title "zsh plugins install"
    type -p git 1>/dev/null || { echo "git is required"; exit 1; }

    [[ -d "${ZSH_PLUGINS_PATH}" ]] || install -d -m 700 "${ZSH_PLUGINS_PATH}"
    local INSTALL_PATH=""

    INSTALL_PATH="${ZSH_PLUGINS_PATH}/zsh-autosuggestions"
    rm -rf "${INSTALL_PATH}" &>/dev/null
    git clone https://github.com/zsh-users/zsh-autosuggestions.git "${INSTALL_PATH}"

    INSTALL_PATH="${ZSH_PLUGINS_PATH}/zsh-syntax-highlighting"
    rm -rf "${INSTALL_PATH}" &>/dev/null
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${INSTALL_PATH}"

    INSTALL_PATH="${ZSH_PLUGINS_PATH}/zsh-history-substring-search"
    rm -rf "${INSTALL_PATH}" &>/dev/null
    git clone https://github.com/zsh-users/zsh-history-substring-search "${INSTALL_PATH}"
}

# wiz is not yet included in mise registry
install_wiz() {
    _draw_title "wiz install"

    cd "${SCRIPT_DIR}" || exit 1
    curl --proto "=https" --tlsv1.2 -fLSs https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 --output wizcli
    chmod a+x ./wizcli
}

if [[ "${OS}" == "fedora" ]]; then
    _draw_title "install dnf packages"
    sudo dnf copr --assumeyes enable jdxcode/mise
    sudo dnf copr --assumeyes enable atim/starship
    sudo dnf copr --assumeyes enable zeno/scrcpy
    sudo dnf update

    FEDORA_PACKAGES=(
        make
        automake
        gcc
        gcc-c++
        kernel-devel
    )
    LINUX_PACKAGES=(
        dconf-editor
        gparted
        rpi-imager
        terminator
        traceroute
        #install_wiz
        #ngrok
    )
    COMMON_PACKAGES=(
        btop
        git
        git-delta
        jq
        micro
        mise
        ncdu
        nmap
        scrcpy
        starship
        xmlstarlet
        yq
    )
    sudo dnf install --assumeyes "${FEDORA_PACKAGES[@]}" "${LINUX_PACKAGES[@]}" "${COMMON_PACKAGES[@]}"
    _show_message_mise
fi

if [[ "${OS}" == "darwin" ]]; then
    _draw_title "install brew packages"
    type -p brew 1>/dev/null || { echo "brew is required"; exit 1; }
    brew update && brew upgrade

    CASK_PACKAGES=(
        ghostty
        wizcli
    )
    brew install --cask "${CASK_PACKAGES[@]}"

    COMMON_PACKAGES=(
        btop
        git
        git-delta
        jq
        micro
        mise
        ncdu
        nmap
        scrcpy
        starship
        xmlstarlet
        yq
    )
    brew install "${COMMON_PACKAGES[@]}"
    #    brew install                                                                                  \
    #         colima                        docker                         docker-compose              \
    #         docker-credential-helper
    _show_message_mise
fi

_install_zsh_plugins

_draw_spacer

type -p mise 1>/dev/null || { echo "mise is required"; exit 1; }
mise use --global act@latest
mise use --global actionlint@latest
mise use --global awscli@latest
mise use --global bat@latest
mise use --global circleci@latest
mise use --global claude@latest
mise use --global dagger@latest
mise use --global flutter@latest
mise use --global gh@latest
mise use --global jmespath@latest
mise use --global lazygit@latest
mise use --global node@latest
mise use --global poetry@latest
mise use --global rtk@latest && {
    cat <<"EOF"
    rtk init --global
    rtk init --global --gemini
EOF
}
mise use --global rust@latest && {
    cat <<"EOF"
    rustup component list --installed
    cargo install --list

    rustup component add rust-analyzer
    cargo install cargo-cache
    cargo install cargo-lambda
    cargo install cargo-watch
EOF
}
mise use --global terraform@latest
mise use --global terraform-docs@latest && {
    cat <<"EOF"
    [[ -f "${BIN_PATH}/bin/terraform-docs" ]] && eval "$(terraform-docs completion zsh)"
EOF
}
mise use --global terragrunt@latest && {
    cat <<"EOF"
    [[ -f "${BIN_PATH}/bin/terragrunt" ]] && complete -o nospace -C "${BIN_PATH}/bin/terragrunt" terragrunt
EOF
}
mise use --global tflint@latest
mise use --global uv@latest
mise use --global yamllint@latest

_draw_spacer

# cargo install aws-mfa
